#!/bin/env python

import os
import sys
import difflib
import time

#os.system
port = sys.argv[1]
proxy = "comp112-02.cs.tufts.edu"
url0 = "https://arxiv.org/pdf/1707.03264.pdf"
url1 = "http://www.cs.cmu.edu/~prs/bio.html"
url2 = "https://www.google.com/"
url3 = "http://portquiz.net:8080/"
url4 = "http://www.arcanedomain.com/Noahhead.jpg"
url5 = "www.cs.tufts.edu/comp/160/"



#Test 1: Text Based Files
os.system("curl -s " + url1 + " > real")
os.system("curl -s -x " + proxy + ":" + port + " " + url1 + " > ours")

# sys.exit()

if (os.system("diff real ours") == 0):
    print ("--------- TEST 1 (GET Text file diff) PASSED --------")
else:
    print ("--------- TEST 1 (GET Test file diff) FAILED --------")


os.system("rm real")
os.system("rm ours")

#Test 2: JPG files

os.system("curl -s " + url4 + " > real")
os.system("curl -s -x " + proxy + ":" + port + " " + url4 + " > ours")


if (os.system("diff real ours") == 0):
    print ("--------- TEST 2 (GET JPG file diff) PASSED --------")
else:
    print ("--------- TEST 2 (GET JPG file diff) FAILED --------")


os.system("rm real")
os.system("rm ours")

# sys.exit()

#Test 3: Inserting and fetching from cache - test passes based on time it took to retrieve

start = time.time()
os.system("curl -s -x " + proxy + ":" + port + " " + url3 + " > temp")
end = time.time()
noCache = end - start

start = time.time()
os.system("curl -s -x " + proxy + ":" + port + " " + url3 + " > temp")
end = time.time()
cache = end - start
if (cache < noCache):
    print ("--------- TEST 3 (Insert and fetch from cache) PASSED --------")
else:
    print ("--------- TEST 3 (Insert and fetch from cache) FAILED --------")

os.system("rm temp")

#Test 4: Test eviction policy
os.system("curl -s -x " + proxy + ":" + port + " " + url5 + " > temp")

print ("--------- TEST 4 (Eviction from cache assuming cache size = 3) CHECK SERVER LOGS --------")

os.system("rm temp")


#Test 5: Test CONNECT
os.system("curl -s -x " + proxy + ":" + port + " " + url0 + "> ours")
os.system("curl -s " + url0 + "> real")


if (os.system("diff real ours") == 0):
    print ("--------- TEST 5 (CONNECT diff) PASSED --------")
else:
    print ("--------- TEST 5 (CONNECT diff) FAILED --------")

os.system("rm ours real")
