#!/bin/bash

# set proxy value to communicate with your desired machine
PROXY='comp112-02.cs.tufts.edu'

# set the resource value to request the desired resource
RESRC='http://www.cs.cmu.edu/~prs/bio.html'

curl -x $PROXY:$1 $RESRC
